AWSTemplateFormatVersion: '2010-09-09'
Description: |
  MasterProject Governance Infrastructure
  Creates CloudTrail for audit logging and AWS Config for compliance monitoring.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  Project:
    Type: String
    Default: MasterProject
    Description: Project name for resource tagging

  CloudTrailLogRetentionDays:
    Type: Number
    Default: 90
    Description: Days to retain CloudTrail logs before transitioning to Glacier

  ConfigDeliveryFrequency:
    Type: String
    Default: TwentyFour_Hours
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours
    Description: AWS Config delivery frequency

Resources:
  # ============================================================================
  # CloudTrail S3 Bucket
  # ============================================================================
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mp-cloudtrail-logs-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: !Ref CloudTrailLogRetentionDays
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 365
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-cloudtrail-logs'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailBucket.Arn
            Condition:
              StringEquals:
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/MasterProjectTrail'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${CloudTrailBucket.Arn}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/MasterProjectTrail'

  # ============================================================================
  # CloudWatch Log Group for CloudTrail
  # ============================================================================
  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/cloudtrail/masterproject
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-cloudtrail-logs'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  CloudTrailLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Project}-${Environment}-cloudtrail-logs-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt CloudTrailLogGroup.Arn
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-cloudtrail-logs-role'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # ============================================================================
  # CloudTrail Trail
  # ============================================================================
  MasterProjectTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailBucketPolicy
    Properties:
      TrailName: MasterProjectTrail
      S3BucketName: !Ref CloudTrailBucket
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsLogging: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailLogRole.Arn
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources: []
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-trail'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # ============================================================================
  # AWS Config S3 Bucket
  # ============================================================================
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mp-config-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldConfigs
            Status: Enabled
            ExpirationInDays: 365
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-config'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt ConfigBucket.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: AWSConfigBucketExistenceCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:ListBucket
            Resource: !GetAtt ConfigBucket.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${ConfigBucket.Arn}/AWSLogs/${AWS::AccountId}/Config/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceAccount: !Ref AWS::AccountId

  # ============================================================================
  # AWS Config IAM Role
  # ============================================================================
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Project}-${Environment}-config-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole
      Policies:
        - PolicyName: ConfigS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub '${ConfigBucket.Arn}/AWSLogs/${AWS::AccountId}/Config/*'
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                Resource: !GetAtt ConfigBucket.Arn
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-config-role'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # ============================================================================
  # AWS Config Recorder
  # ============================================================================
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: !Sub '${Project}-${Environment}-recorder'
      RoleARN: !GetAtt ConfigRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  # ============================================================================
  # AWS Config Delivery Channel
  # ============================================================================
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn: ConfigBucketPolicy
    Properties:
      Name: !Sub '${Project}-${Environment}-delivery-channel'
      S3BucketName: !Ref ConfigBucket
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref ConfigDeliveryFrequency

  # ============================================================================
  # AWS Config Rules
  # ============================================================================
  
  # Rule 1: S3 Bucket Public Read Prohibited
  S3BucketPublicReadProhibited:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: s3-bucket-public-read-prohibited
      Description: Checks that S3 buckets do not allow public read access
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED
      MaximumExecutionFrequency: TwentyFour_Hours

  # Rule 2: S3 Bucket Public Write Prohibited
  S3BucketPublicWriteProhibited:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: s3-bucket-public-write-prohibited
      Description: Checks that S3 buckets do not allow public write access
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
      MaximumExecutionFrequency: TwentyFour_Hours

  # Rule 3: Restricted SSH
  RestrictedSSH:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: restricted-ssh
      Description: Checks that security groups do not allow unrestricted SSH access (0.0.0.0/0 on port 22)
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED

  # Rule 4: CloudTrail Enabled
  CloudTrailEnabled:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: cloudtrail-enabled
      Description: Checks that CloudTrail is enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  # Rule 5: EC2 Managed by Systems Manager
  EC2ManagedBySSM:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ec2-instance-managed-by-systems-manager
      Description: Checks that EC2 instances are managed by Systems Manager
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_MANAGED_BY_SSM

# ============================================================================
# Outputs
# ============================================================================
Outputs:
  CloudTrailBucketName:
    Description: CloudTrail S3 Bucket Name
    Value: !Ref CloudTrailBucket
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailBucket'

  CloudTrailBucketArn:
    Description: CloudTrail S3 Bucket ARN
    Value: !GetAtt CloudTrailBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailBucketArn'

  CloudTrailArn:
    Description: CloudTrail Trail ARN
    Value: !GetAtt MasterProjectTrail.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailArn'

  CloudTrailLogGroupName:
    Description: CloudTrail CloudWatch Log Group Name
    Value: !Ref CloudTrailLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailLogGroup'

  ConfigBucketName:
    Description: AWS Config S3 Bucket Name
    Value: !Ref ConfigBucket
    Export:
      Name: !Sub '${AWS::StackName}-ConfigBucket'

  ConfigBucketArn:
    Description: AWS Config S3 Bucket ARN
    Value: !GetAtt ConfigBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ConfigBucketArn'

  ConfigRoleArn:
    Description: AWS Config IAM Role ARN
    Value: !GetAtt ConfigRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ConfigRoleArn'

  StackName:
    Description: Stack name for cross-stack references
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub '${AWS::StackName}-StackName'
